### ISSUE TITLE
Incorrect drc-20 balances

### ISSUE THREAD

**Issue by decentraliser** [verydogelabs/wonky-ord-dogecoin#11]
Hi!

Is this repo in production for DRC-20?

I've done a full sync with the current master branch, when I compare balances from my node to drc-20.org and doggy.market, balances are far off for most tokens.

I'm wondering if you are using `wonky-ord-dogecoin` or `drc20-indexer` in prod, and if there are some known issues around DRC-20

Cheers!

**Comment by artdoge** [comment]
Hey @decentraliser, thanks for writing. Can you provide your exact config, you started your ord with?

**Comment by decentraliser** [comment]
Hi!

Here is the startup command I used, I did not use a .env file

```
ordd [...] --nr-parallel-requests=16 --first-inscription-height=4609723 --first-dune-height=5084000 --index-dunes --index-
transactions --index-drc20 server --http-port 8080
```

**Comment by artdoge** [comment]
@decentraliser just fyi: we are currently investigating and will come back soon to you.

**Comment by dogeveloper** [comment]
Fixed by https://github.com/verydogelabs/wonky-ord-dogecoin/pull/12

**Comment by artdoge** [comment]
@decentraliser it is fixed now. Thanks for bringing it up!
