### ISSUE TITLE
Inscription text content often fails to display

### ISSUE THREAD

**Issue by natureisbestNFT** [verydogelabs/wonky-ord-dogecoin#3]
eg at http://127.0.0.1:port_number/shibescription/b28d30d95b967058e04947c6b87764c6ea594c24efb6dc020a2caca0b94570dfi0 it just shows a blank space for the content. You have to click on the 'content' link to see it.

**Comment by natureisbestNFT** [comment]
This is probably because some of the previews are empty. eg
https://wonky-ord.dogeord.io/preview/3d06bdeb8981a636d1954dd1c3307e8b99d84c05c8e82e47690ecdbe05875b7fi0
says

<!doctype html>
<html lang=en>
  <head>
    <meta charset=utf-8>
  </head>
  <body>
  </body>
</html>

even though the real content is a drc-20 deploy inscription.

**Comment by dogeveloper** [comment]
Fixed by https://github.com/verydogelabs/wonky-ord-dogecoin/pull/12
