### ISSUE TITLE
SUBSIDIES_PATH must be set

### ISSUE THREAD

**Issue by ChristianGrieger** [verydogelabs/wonky-ord-dogecoin#5]
I try to index the client with sat points :)

Could you please give information about the .env file setup? Found this in the code so looks like the .env file needs some information:

lazy_static! {
    pub(crate) static ref STARTING_SATS: Vec<Sat> = {
        let path = env::var("STARTING_SATS_PATH").expect("STARTING_SATS_PATH must be set");
        read_sat_from_file(&path).expect("Failed to read JSON")
    };
}

static EPOCHS: Lazy<Epochs> = Lazy::new(|| {
    let path = env::var("SUBSIDIES_PATH").expect("SUBSIDIES_PATH must be set");
    let data = fs::read_to_string(&path).expect("Unable to read file");
    serde_json::from_str(&data).expect("Unable to parse JSON")
});

This is the error when I start it with --index-sats

thread 'main' panicked at 'SUBSIDIES_PATH must be set: NotPresent', src/epoch.rs:35:43

**Comment by lambodoge** [comment]
Info added to README with [this commit](https://github.com/verydogelabs/wonky-ord-dogecoin/commit/628bc6bc03618a2ca82f1dd5b76d2a969e527310)
