### ISSUE TITLE
 Table 'OUTPOINT_TO_DUNE_BALANCES' does not exist

### ISSUE THREAD

**Issue by Skr1pt** [verydogelabs/wonky-ord-dogecoin#9]
Table 'OUTPOINT_TO_DUNE_BALANCES' does not exist 
when start index

**Comment by dogeveloper** [comment]
Currently the tables for dunes are just created after the block height of first dune, which is `5084000`

**Comment by toregua** [comment]
I have the same behavior, the fact that the table does not exists during drc20 indexing is triggering an issue in output and for me it seem to impact drc20 balance.

To avoid that personaly i have replaced this code : 

`let outpoint_to_balances = rtx.open_table(OUTPOINT_TO_DUNE_BALANCES)?;`

by

```
let outpoint_to_balances = match rtx.open_table(OUTPOINT_TO_DUNE_BALANCES) {
  Ok(table) => table,
  Err(_) => return Ok(Vec::new()),
};
```

in the get_dune_balances_for_outpoint method in index.rs file

It will avoid the issue when the table does not existe yet until the first dune block

**Comment by Skr1pt** [comment]
> I have the same behavior, the fact that the table does not exists during drc20 indexing is triggering an issue in output and for me it seem to impact drc20 balance.
> 
> To avoid that personaly i have replaced this code :
> 
> `let outpoint_to_balances = rtx.open_table(OUTPOINT_TO_DUNE_BALANCES)?;`
> 
> by
> 
> ```
> let outpoint_to_balances = match rtx.open_table(OUTPOINT_TO_DUNE_BALANCES) {
>   Ok(table) => table,
>   Err(_) => return Ok(Vec::new()),
> };
> ```
> 
> in the get_dune_balances_for_outpoint method in index.rs file
> 
> It will avoid the issue when the table does not existe yet until the first dune block

thank you

**Comment by dogeveloper** [comment]
Fixed by https://github.com/verydogelabs/wonky-ord-dogecoin/pull/12
